-- NOME E DATA DE NASCIMENTO DE TODOS OS CLIENTES
SELECT NOME, DATA_NASCIMENTO FROM CLIENTE;

-- NOME E DATA DE NASCIMENTO DE TODOS OS CLIENTES ORDENADO ALFABETICAMENTE
SELECT NOME, DATA_NASCIMENTO FROM CLIENTE ORDER BY NOME ASC;

-- NOME E DATA DE NASCIMENTO DOS CLIENTES QUE SE CHAMAM ANA
SELECT NOME, DATA_NASCIMENTO FROM CLIENTE WHERE NOME='ANA';

-- NOME E DATA DE NASCIMENTO DE TODOS OS CLIENTES CUJO NOME COMEÇA COM A
SELECT NOME, DATA_NASCIMENTO FROM CLIENTE WHERE NOME LIKE 'A%';

-- NOME E DATA DE NASCIMENTO DE TODOS OS CLIENTES CUJO NOME TERMINA EM A;
SELECT NOME, DATA_NASCIMENTO FROM CLIENTE WHERE NOME LIKE '%A';

-- NUMERO DOS QUARTOS DO HOTEL QUE TEM COMO NOME "HOTEL 1"
-- OPCAO 1 --
SELECT NUMERO FROM QUARTO INNER JOIN HOTEL ON QUARTO.IDHOTEL=HOTEL.IDENTIFICADOR WHERE HOTEL.NOME='HOTEL 1';

-- OPCAO 2 --
SELECT NUMERO FROM QUARTO WHERE QUARTO.IDHOTEL IN (
SELECT IDHOTEL FROM HOTEL WHERE NOME="HOTEL 1");

-- NOME DOS FUNCIONARIOS DO HOTEL COM O NOME "HOTEL 1"
SELECT NOME FROM FUNCIONARIO WHERE FUNCIONARIO.IDHOTEL IN (
SELECT IDHOTEL FROM HOTEL WHERE NOME="HOTEL 1");

-- CONTAGEM DE QUARTOS LIVRES, POR HOTEL
SELECT COUNT(NUMERO) FROM QUARTO GROUP BY IDHOTEL;

-- NOME DOS FUNCIONARIOS CUJA FUNÇÃO TEM A DESCRIÇÃO DE RECEPCIONISTA
SELECT ID FROM FUNCAO WHERE DESCRICAO LIKE '%RECEPCIONISTA%';

-- OPÇÃO 1 -- SUBQUERY
SELECT NOME FROM FUNCIONARIOS WHERE IDFUNCAO IN (
SELECT ID FROM FUNCAO WHERE DESCRICAO LIKE '%RECEPCIONISTA%');

-- OPÇÃO 2 -- JOIN
SELECT FUNCIONARIOS.NOME FROM FUNCIONARIOS
INNER JOIN FUNCAO ON FUNCIONARIOS.IDFUNCAO=FUNCAO.ID
WHERE FUNCAO.DESCRICAO LIKE '%RECEPCIONISTA%';

--

