#include <stdio.h>

int main(){
	char names[][] = {
	"João Silva",
	"Maria Santos",
	"José Oliveira",
	"Ana Pereira",
	"Manuel Costa",
	"Isabel Ferreira",
	"António Martins",
	"Teresa Rodrigues",
	"Francisco Almeida",
	"Margarida Pinheiro",
	"Carlos Carvalho",
	"Sofia Ribeiro",
	"Pedro Henriques",
	"Catarina Gomes",
	"Miguel Lopes",
	"Paula Vieira",
	"Paulo Fernandes",
	"Helena Pinto",
	"Luís Sousa",
	"Rita Morais",
	"Fernando Santos",
	"Laura Marques",
	"Jorge Gonçalves",
	"Patrícia Jesus",
	"Rui Barbosa",
	"Diana Matos",
	"Ricardo Pacheco",
	"Inês Correia",
	"Daniel Rebelo",
	"Lúcia Castro",
	"Alexandre Costa",
	"Sílvia Fernandes",
	"Tiago Oliveira",
	"Marta Carvalho",
	"David Martins",
	"Carla Pereira",
	"Nuno Silva",
	"Andreia Costa",
	"Fernando Mendes",
	"Beatriz Ramos",
	"Filipe Santos",
	"Liliana Ferreira",
	"Vasco Rocha",
	"Mariana Teixeira",
	"Gonçalo Duarte",
	"Cláudia Santos",
	"Bruno Ramos",
	"Andreia Martins",
	"Marcelo Pereira",
	"Leonor Silva",
	"Vítor Oliveira",
	"Lígia Rodrigues",
	"Tomás Sousa",
	"Mónica Santos",
	"Sérgio Almeida",
	"Joana Silva",
	"Diogo Carvalho",
	"Vera Fernandes",
	"Eduardo Costa",
	"Sofia Pires",
	"Artur Rodrigues",
	"Marta Oliveira",
	"Nelson Pereira",
	"Sónia Silva",
	"Orlando Carvalho",
	"Bárbara Martins",
	"Amílcar Fernandes",
	"Adriana Costa",
	"Gabriel Silva",
	"Ângela Pereira",
	"Hélder Santos",
	"Andreia Oliveira",
	"Simão Carvalho",
	"Susana Rodrigues",
	"Dário Mendes",
	"Patrícia Gomes",
	"Agostinho Ferreira",
	"Tânia Santos",
	"Abel Pereira",
	"Filipa Silva",
	"Adriano Costa",
	"Lúcia Oliveira",
	"Armando Martins",
	"Sara Rodrigues",
	"Baltazar Silva",
	"Natália Santos",
	"Belmiro Ferreira",
	"Eunice Oliveira",
	"Camilo Costa",
	"Tatiana Silva",
	"Celestino Rodrigues",
	"Goreti Pereira",
	"Clemente Fernandes",
	"Hortênsia Santos",
	"Custódio Martins",
	"Janete Silva",
	"Delfim Pereira",
	"Leontina Fernandes",
	"Diamantino Santos",
	"Odete Oliveira",



	"joao.silva@example.com",
	"maria.santos@example.com",
	"jose.oliveira@example.com",
	"ana.pereira@example.com",
	"manuel.costa@example.com",
	"isabel.ferreira@example.com",
	"antonio.martins@example.com",
	"teresa.rodrigues@example.com",
	"francisco.almeida@example.com",
	"margarida.pinheiro@example.com",
	"carlos.carvalho@example.com",
	"sofia.ribeiro@example.com",
	"pedro.henriques@example.com",
	"catarina.gomes@example.com",
	"miguel.lopes@example.com",
	"paula.vieira@example.com",
	"paulo.fernandes@example.com",
	"helena.pinto@example.com",
	"luis.sousa@example.com",
	"rita.morais@example.com",
	"fernando.santos@example.com",
	"laura.marques@example.com",
	"jorge.goncalves@example.com",
	"patricia.jesus@example.com",
	"rui.barbosa@example.com",
	"diana.matos@example.com",
	"ricardo.pacheco@example.com",
	"ines.correia@example.com",
	"daniel.rebelo@example.com",
	"lucia.castro@example.com",
	"alexandre.costa@example.com",
	"silvia.fernandes@example.com",
	"tiago.oliveira@example.com",
	"marta.carvalho@example.com",
	"david.martins@example.com",
	"carla.pereira@example.com",
	"nuno.silva@example.com",
	"andreia.costa@example.com",
	"fernando.mendes@example.com",
	"beatriz.ramos@example.com",
	"filipe.santos@example.com",
	"liliana.ferreira@example.com",
	"vasco.rocha@example.com",
	"mariana.teixeira@example.com",
	"goncalo.duarte@example.com",
	"claudia.santos@example.com",
	"bruno.ramos@example.com",
	"andreia.martins@example.com",
	"marcelo.pereira@example.com",
	"leonor.silva@example.com",
	"vitor.oliveira@example.com",
	"ligia.rodrigues@example.com",
	"tomas.sousa@example.com",
	"monica.santos@example.com",
	"sergio.almeida@example.com",
	"joana.silva@example.com",
	"diogo.carvalho@example.com",
	"vera.fernandes@example.com",
	"eduardo.costa@example.com",
	"sofia.pires@example.com",
	"artur.rodrigues@example.com",
	"marta.oliveira@example.com",
	"nelson.pereira@example.com",
	"sonia.silva@example.com",
	"orlando.carvalho@example.com",
	"barbara.martins@example.com",
	"amilcar.fernandes@example.com",
	"adriana.costa@example.com",
	"gabriel.silva@example.com",
	"angela.pereira@example.com",
	"helder.santos@example.com",
	"andreia.oliveira@example.com",
	"simao.carvalho@example.com",
	"susana.rodrigues@example.com",
	"dario.mendes@example.com",
	"patricia.gomes@example.com",
	"agostinho.ferreira@example.com",
	"tania.santos@example.com",
	"abel.pereira@example.com",
	"filipa.silva@example.com",
	"adriano.costa@example.com",
	"lucia.oliveira@example.com",
	"armando.martins@example.com",
	"sara.rodrigues@example.com",
	"baltazar.silva@example.com",
	"natalia.santos@example.com",
	"belmiro.ferreira@example.com",
	"eunice.oliveira@example.com",
	"camilo.costa@example.com",
	"tatiana.silva@example.com",
	"celestino.rodrigues@example.com",
	"goreti.pereira@example.com",
	"clemente.fernandes@example.com",
	"hortensia.santos@example.com",
	"custodio.martins@example.com",
	"janete.silva@example.com",
	"delfim.pereira@example.com",
	"leontina.fernandes@example.com",
	"diamantino.santos@example.com",
	"odete.oliveira@example.com",
	};
}
